"""adicionando tabela cliente

Revision ID: 034acb1ee6ae
Revises: 1c78b65d2d33
Create Date: 2025-04-20 18:55:09.171759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '034acb1ee6ae'
down_revision = '1c78b65d2d33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('dtcadastro', sa.DateTime(), nullable=False),
    sa.Column('nome', sa.String(length=20), nullable=False),
    sa.Column('sobrenome', sa.String(length=50), nullable=False),
    sa.Column('genero', sa.String(length=1), nullable=False),
    sa.Column('cpf', sa.Integer(), nullable=False),
    sa.Column('rg', sa.Integer(), nullable=False),
    sa.Column('dt_nascimento', sa.DateTime(), nullable=False),
    sa.Column('estado_civil', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('telefone', sa.Integer(), nullable=False),
    sa.Column('rua', sa.String(length=100), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=True),
    sa.Column('complemento', sa.String(length=100), nullable=True),
    sa.Column('bairro', sa.String(length=50), nullable=False),
    sa.Column('cidade', sa.String(length=50), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('plano', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['plano'], ['plano.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('rg')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cliente')
    # ### end Alembic commands ###
