"""Inserindo tabela checki

Revision ID: 064ab701703c
Revises: 82c443a14c14
Create Date: 2025-04-21 10:26:03.996863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '064ab701703c'
down_revision = '82c443a14c14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_cliente_plano', 'plano', ['plano'], ['id'], ondelete='RESTRICT')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.drop_constraint('fk_cliente_plano', type_='foreignkey')
        batch_op.create_foreign_key(None, 'plano', ['plano'], ['id'])

    # ### end Alembic commands ###
