"""editando plano, adicionando coluna categoria

Revision ID: 1c78b65d2d33
Revises: 51e040a5a5e0
Create Date: 2025-04-20 14:48:14.099816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c78b65d2d33'
down_revision = '51e040a5a5e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plano', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categoria', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plano', schema=None) as batch_op:
        batch_op.drop_column('categoria')

    # ### end Alembic commands ###
