"""adicionando restrição de exclusão de chave extrangeira no plano

Revision ID: 50f0207e2d5c
Revises: 034acb1ee6ae
Create Date: 2025-04-21 07:16:13.484062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50f0207e2d5c'
down_revision = '034acb1ee6ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'plano', ['plano'], ['id'], ondelete='RESTRICT')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'plano', ['plano'], ['id'])

    # ### end Alembic commands ###
