"""Inserindo tabela checkin

Revision ID: 641bc78edc81
Revises: cb67bade4cac
Create Date: 2025-04-21 10:30:31.460052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '641bc78edc81'
down_revision = 'cb67bade4cac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checkin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dt_checkin', sa.DateTime(), nullable=False),
    sa.Column('dt_checkout', sa.DateTime(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], name='fk_checkin_cliente'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('checkin')
    # ### end Alembic commands ###
