"""criação das tabelas iniciais

Revision ID: 6923e35cfdc3
Revises: 
Create Date: 2025-04-24 16:15:47.877910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6923e35cfdc3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plano',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('dtcadastro', sa.DateTime(), nullable=False),
    sa.Column('plano', sa.String(length=50), nullable=False),
    sa.Column('preco', sa.Float(), nullable=False),
    sa.Column('categoria', sa.String(length=20), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('dtcadastro', sa.DateTime(), nullable=False),
    sa.Column('nome', sa.String(length=20), nullable=False),
    sa.Column('sobrenome', sa.String(length=50), nullable=False),
    sa.Column('genero', sa.String(length=1), nullable=False),
    sa.Column('cpf', sa.BigInteger(), nullable=False),
    sa.Column('rg', sa.BigInteger(), nullable=False),
    sa.Column('dt_nascimento', sa.DateTime(), nullable=False),
    sa.Column('estado_civil', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('telefone', sa.BigInteger(), nullable=False),
    sa.Column('rua', sa.String(length=100), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=True),
    sa.Column('complemento', sa.String(length=100), nullable=True),
    sa.Column('bairro', sa.String(length=50), nullable=False),
    sa.Column('cidade', sa.String(length=50), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('plano', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['plano'], ['plano.id'], name='fk_cliente_plano'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('rg')
    )
    op.create_table('checkin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dt_checkin', sa.DateTime(), nullable=False),
    sa.Column('dt_checkout', sa.DateTime(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], name='fk_checkin_cliente'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('checkin')
    op.drop_table('cliente')
    op.drop_table('plano')
    # ### end Alembic commands ###
